name: rohrreinigung-meissner
region: fra
static_sites:
  - name: web
    github:
      repo: yarek98/rohrreinigung-meissner
      branch: main
      deploy_on_push: true
    source_dir: /
    output_dir: /
    index_document: index.html
    catchall_document: index.html
domains:
  - domain: rohrreinigung-meissner.de
    type: PRIMARY
    zone: rohrreinigung-meissner.de
  - domain: www.rohrreinigung-meissner.de
    type: ALIAS
    zone: rohrreinigung-meissner.de
